# -*- coding: utf-8 -*-
#############################################################################
#
#    Cyllo Pvt. Ltd.
#
#    Copyright (C) 2025-TODAY Cyllo(<https://www.cyllo.com>)
#    Author: Cyllo(<https://www.cyllo.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
from odoo import fields
from odoo.tests import common, tagged


@tagged('post_install', '-at_install')
class TestStockPickingCarbon(common.TransactionCase):
    """Tests for the carbon footprint generated by inventory transfers."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.company = cls.env.company
        cls.unit = cls.env['carbon.unit'].create({
            'name': 'kgCO2e-transfer-test',
            'symbol': 'kg',
        })
        cls.source = cls.env['carbon.source'].create({
            'name': 'Outbound Delivery Fuel',
            'category': 'other',
            'activity_unit': cls.unit.id,
        })
        cls.factor = cls.env['carbon.factor'].create({
            'name': 'Delivery Air Factor',
            'source_id': cls.source.id,
            'factor_value': 2.5,
            'type': 'air',
            'unit_name': cls.unit.id,
        })
        cls.picking_type = cls.env.ref('stock.picking_type_out')
        cls.partner = cls.env['res.partner'].create({'name': 'Carbon Customer'})
        cls.product = cls.env['product.product'].create({
            'name': 'Carbon Tracked Product',
            'type': 'consu',
        })
        cls.carbon_line = cls.env['stock.picking.type.carbon'].create({
            'picking_type_id': cls.picking_type.id,
            'source_id': cls.source.id,
        })

    def _create_picking(self, quantity=4.0, partner=None, product=None):
        product = product or self.product
        picking = self.env['stock.picking'].create({
            'partner_id': (partner or self.partner).id,
            'picking_type_id': self.picking_type.id,
            'location_id': self.picking_type.default_location_src_id.id,
            'location_dest_id': self.env.ref('stock.stock_location_customers').id,
        })
        self.env['stock.move'].create({
            'name': product.name,
            'product_id': product.id,
            'product_uom_qty': quantity,
            'product_uom': product.uom_id.id,
            'picking_id': picking.id,
            'location_id': picking.location_id.id,
            'location_dest_id': picking.location_dest_id.id,
        })
        picking.action_confirm()
        for move in picking.move_ids:
            move.quantity = quantity
        picking.move_ids.picked = True
        return picking

    # -------------------------------------------------------------------------
    # Configuration model
    # -------------------------------------------------------------------------
    def test_carbon_line_unit_follows_source(self):
        """The unit of a configuration line is taken from its source."""
        self.assertEqual(self.carbon_line.unit_id, self.unit)

    def test_onchange_source_updates_unit(self):
        """Clearing the source clears the unit through the onchange."""
        line = self.env['stock.picking.type.carbon'].new({
            'picking_type_id': self.picking_type.id,
            'source_id': self.source.id,
        })
        line._onchange_source_id()
        self.assertEqual(line.unit_id, self.unit)
        line.source_id = False
        line._onchange_source_id()
        self.assertFalse(line.unit_id)

    def test_picking_type_exposes_carbon_lines(self):
        """The configuration line is reachable from the operation type."""
        self.assertIn(self.carbon_line, self.picking_type.carbon_line_ids)

    def test_carbon_activity_has_picking_field(self):
        """carbon.activity is extended with a link back to the transfer."""
        field = self.env['carbon.activity']._fields.get('picking_id')
        self.assertTrue(field)
        self.assertEqual(field.comodel_name, 'stock.picking')

    # -------------------------------------------------------------------------
    # Validation of a transfer
    # -------------------------------------------------------------------------
    def test_validation_creates_carbon_activity(self):
        """Validating a transfer records one activity per emission factor."""
        picking = self._create_picking(quantity=4.0)
        picking.button_validate()

        activities = self.env['carbon.activity'].search([
            ('picking_id', '=', picking.id),
        ])
        self.assertEqual(len(activities), 1)
        self.assertEqual(activities.source_id, self.source)
        self.assertEqual(activities.factor_id, self.factor)
        self.assertEqual(activities.quantity, 4.0)
        self.assertEqual(activities.date, fields.Date.context_today(picking))
        self.assertEqual(activities.emission_total, 10.0)

    def test_validation_reuses_the_daily_calculation(self):
        """Two transfers on the same day share a single calculation record."""
        first = self._create_picking(quantity=2.0)
        first.button_validate()
        second = self._create_picking(quantity=3.0)
        second.button_validate()

        calculations = self.env['carbon.activity'].search([
            ('picking_id', 'in', (first | second).ids),
        ]).mapped('calculation_id')
        self.assertEqual(len(calculations), 1)
        self.assertEqual(calculations.date, fields.Date.context_today(first))

    def test_no_activity_without_configuration(self):
        """A transfer whose operation type has no source records nothing."""
        self.carbon_line.unlink()
        picking = self._create_picking(quantity=5.0)
        picking.button_validate()
        self.assertFalse(self.env['carbon.activity'].search([
            ('picking_id', '=', picking.id),
        ]))

    def test_partner_filter_is_applied(self):
        """A line restricted to other partners does not generate an activity."""
        other_partner = self.env['res.partner'].create({'name': 'Other Partner'})
        self.carbon_line.partner_ids = [(6, 0, other_partner.ids)]
        picking = self._create_picking(quantity=5.0)
        picking.button_validate()
        self.assertFalse(self.env['carbon.activity'].search([
            ('picking_id', '=', picking.id),
        ]))

    def test_partner_filter_matches(self):
        """A line restricted to the transfer partner does generate an activity."""
        self.carbon_line.partner_ids = [(6, 0, self.partner.ids)]
        picking = self._create_picking(quantity=5.0)
        picking.button_validate()
        self.assertTrue(self.env['carbon.activity'].search([
            ('picking_id', '=', picking.id),
        ]))

    def test_product_filter_is_applied(self):
        """A line restricted to other products does not generate an activity."""
        other_product = self.env['product.product'].create({
            'name': 'Untracked Product',
            'type': 'consu',
        })
        self.carbon_line.product_ids = [(6, 0, other_product.ids)]
        picking = self._create_picking(quantity=5.0)
        picking.button_validate()
        self.assertFalse(self.env['carbon.activity'].search([
            ('picking_id', '=', picking.id),
        ]))
